name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.access_token }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
      - name: Run a one-line script
        run: echo Hello, world!${{ secrets.access_token }}
